##########################################################
#
#           服务器配置
#
##########################################################
server.port=8888
spring.application.name=yunshu-nas
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
##########################################################
#
#           日志配置
#
##########################################################
logging.level.top=debug
